infra:
  redis:
    enabled: false   # 先关闭

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Tokyo
    username: root
    password: Yx19900703.
    driver-class-name: com.mysql.cj.jdbc.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
  web:
    locale: ja_JP
    locale-resolver: fixed
  jackson:
    time-zone: Asia/Tokyo

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      # 先把逻辑删除约定好，后面实体直接用
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    # 仅开发期打印 SQL；生产不要配
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
